apiVersion: v1
kind: Namespace
metadata:
  name: master-cms-base
  labels:
    app: master-cms
    environment: base
    managed-by: terraform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: master-cms-quota
  namespace: master-cms-base
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    services.loadbalancers: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: master-cms-base
  name: master-cms-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: master-cms-rolebinding
  namespace: master-cms-base
subjects:
- kind: ServiceAccount
  name: master-cms-sa
  namespace: master-cms-base
roleRef:
  kind: Role
  name: master-cms-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: master-cms-sa
  namespace: master-cms-base
  labels:
    app: master-cms 